language: java
notifications:
  hipchat:
    rooms:
      secure: NB4eDTi6gjZiWJdcL3raX6an9qFSYX7BxNJ0VG2Ui5W82XAbllzzJsp15g+P8iYH+WZQuNF/+ih0a7rmDdLbzGigmAwdPO8f/YVXtR61Vy5vnMyr/K+wLO+2ggndj+M3TAAHNTqGC73nqrQkSmcMVcF30qce4zbsntblJYBkL8vnKntEe/kSY8s9l7SrU39yQ2S5HxsrlC01mQ3R6rWGHsY04yieWrLiypaLERYfOImzAmalQm6liM2IuRn70JQ2StBIjKSO7diHEMoWV06hPf36895BrNN8nNc5Inw5epH9i8OO8/5S58XQSnqQ/nc8f3g4N0u3VWkQ2NPyFSRpD9GM6LKtrkyoxQO40kotIiym/R0oydUMKwqJPPEYcrBkfoHdDVy9jxiDaFALfDAtb/jJMijsj5TCu0XxTyHXss48qE3+v4Q/NNNKmsRsAxSQvZ27mwZYE5YRSPyRMP7uaVadW7Ql9nnZ8DaPSO8oxqFsabg+ibYS++QUoKoVRpp7NLrrj6zdEzJS0VmMkntUa7JqosIbI+3mAnXmW4k6lT+g/jyGID9GBT0ZSc4xh+FsM9VmTqxN5Wo1k/nmqqXMS+i/88EweSA3PTluRtE9zfxY0lPzBkSkjc1S2PZMsTBeR2vCM54pLhA7tKl3ot8r6WJUqoWCbWaXYEByeDj/OyY=
deploy:
  provider: releases
  api_key:
    secure: g7jCyeElwdutdZGzDTDv2W/9P+X32QFHRwhsQPGnhevCfLZoxm3ZhSCH1eSPvA1yR3P4r7SA+VpYAsTJz7Y9lLLw0dJxjeONeUdLTwIwpdlKKXYOn9JwnWEeFbrVgEhJQKzX5/hA0FCNBIh/rNxCemMF65D+RXzwe68Zlgx0/vWqjq6/9rgMOhcmgSZk5u0L1PrHd/QrqhxS0KJ3U4tNJAp8Y4Z6bqwOE2vEDVaSDfkNAbMNK/v4vWLGcVpeunLPlvHfGuugfieVRPd/dqFvhIOV+j7W8lFdKTYLtfZYNXOuT73VTYTcwi5P/2uWP7EpU/WJ8pT899wCCKLc8+qQCGNYQM/B5QqRjsMod5gqsR2op7UN4i9M+U5uwOVKPMACZ0zWWi/DazN8bbhTNfgzqSL8KEsYAFSk5azwKHXfa5JQnumjz8Op7Tbw7EQD8fIurdld66qblbfby2wCbuX3IaOSVG6TfzweZC3hEZ0r5WfbkNJCiu0tcn/U3PgoZLH/KzhYIU5LUgQ/LnREZggk9se4hdNdq5iplFKgcCkHD/1DHqZamN3FOAOGAaBx4gmQw3MbS8wZIsVYYBNBpL0M2e6a1jNEn0Jpm5jy1azWvQNragaEwbUQD/K+UXaJL02nIU9/Q7xYf6BXs0TgJMyS9Ue3zccn3k8TDJqTQ553JGw=
  file_glob: true
  file: build/distributions/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-jira-plugin
